export const GET_TOKEN = "GET_TOKEN";
export const SET_TOKEN = "SET_TOKEN";
export const GET_REFRESH = "GET_REFRESH";
export const SET_REFRESH = "SET_REFRESH";
export const LOGOUT = "LOGOUT";

export const GET_FEATURED = "GET_FEATURED";
export const SET_FEATURED = "SET_FEATURED";
export const GET_NEW_RELEASES = "GET_NEW_RELEASES";
export const SET_NEW_RELEASES = "SET_NEW_RELEASES";

export const GET_USER_DATA = "GET_USER_DATA";
export const SET_USER_DATA = "SET_USER_DATA";
export const GET_USER_TOP_TRACKS = "GET_USER_TOP_TRACKS";
export const SET_USER_TOP_TRACKS = "SET_USER_TOP_TRACKS";
export const GET_USER_TOP_ARTISTS = "GET_USER_TOP_ARTISTS";
export const SET_USER_TOP_ARTISTS = "SET_USER_TOP_ARTISTS";
export const GET_USER_PLAYLISTS = "GET_USER_PLAYLISTS";
export const SET_USER_PLAYLISTS = "SET_USER_PLAYLISTS";

export const GET_PLAYLIST = "GET_PLAYLIST";
export const SET_PLAYLIST = "SET_PLAYLIST";
export const GET_MORE_PLAYLIST_TRACKS = "GET_MORE_PLAYLIST_TRACKS";
export const SET_MORE_PLAYLIST_TRACKS = "SET_MORE_PLAYLIST_TRACKS";

export const SET_CURRENT = "SET_CURRENT";

export const GET_SEARCH_RESULT = "GET_SEARCH_RESULT";
export const SET_SEARCH = "SET_SEARCH";
export const SET_SEARCH_TOGGLE = "SET_SEARCH_TOGGLE";

export const GET_ALBUM = "GET_ALBUM";
export const SET_ALBUM = "SET_ALBUM";

export const GET_ARTIST = "GET_ARTIST";
export const SET_ARTIST = "SET_ARTIST";
export const GET_ARTIST_TOP_TRACKS = "GET_ARTIST_TOP_TRACKS";
export const SET_ARTIST_TOP_TRACKS = "SET_ARTIST_TOP_TRACKS";
export const GET_ARTIST_ALBUMS = "GET_ARTIST_ALBUMS";
export const SET_ARTIST_ALBUMS = "SET_ARTIST_ALBUMS";

export const GET_LIBRARY_ARTISTS = "GET_LIBRARY_ARTISTS";
export const SET_LIBRARY_ARTISTS = "SET_LIBRARY_ARTISTS";
export const GET_LIBRARY_ALBUMS = "GET_LIBRARY_ALBUMS";
export const SET_LIBRARY_ALBUMS = "SET_LIBRARY_ALBUMS";
export const GET_LIBRARY_TRACKS = "GET_LIBRARY_TRACKS";
export const SET_LIBRARY_TRACKS = "SET_LIBRARY_TRACKS";
export const GET_LIBRARY_PLAYLISTS = "GET_LIBRARY_PLAYLISTS";
export const SET_LIBRARY_PLAYLISTS = "SET_LIBRARY_PLAYLISTS";
export const SET_LIBRARY_TOGGLE = "SET_LIBRARY_TOGGLE";
export const GET_MORE_LIBRARY_TRACKS = "GET_MORE_LIBRARY_TRACKS";
export const SET_MORE_LIBRARY_TRACKS = "SET_MORE_LIBRARY_TRACKS";

export const GET_CATEGORY_LIST = "GET_CATEGORY_LIST";
export const SET_CATEGORY_LIST = "SET_CATEGORY_LIST";
export const GET_CATEGORY_DATA = "GET_CATEGORY_DATA";
export const SET_CATEGORY_DATA = "SET_CATEGORY_DATA";
export const GET_CATEGORY_PLAYLISTS = "GET_CATEGORY_PLAYLISTS";
export const SET_CATEGORY_PLAYLISTS = "SET_CATEGORY_PLAYLISTS";
