version: 2.1
jobs:
  build:
    docker:
      - image: node:11.10.1

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  build:
    jobs:
      - build
